### PR TITLE
Crash if LTC is selected

### PR DESCRIPTION
**Pull request by dstuecken**
Fixing unexpected crashes if LTC is configured to show in the menubar

### CODE REVIEW

**Review by stefanmendoza — COMMENTED** [review]
Indentation looks off in a couple places.

**Comment by stefanmendoza** [comment]
Also, do you need to rebuild the .zip to include the new changes?

**Comment by dstuecken** [comment]
Oh yea it's tab-based indentation. Should I change that?

What do you mean do you need to rebuild the zip?

**Comment by dai-cb** [comment]
Closing, these were fixed in #9

**Pull request closed without merging**
